// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGTmcnwvwkK2cZLcU5Cipaefjuqq1QxQ',
    appId: '1:717511155216:web:8ef5eb699d17f8d22eb495',
    messagingSenderId: '717511155216',
    projectId: 'clinify-2d47a',
    authDomain: 'clinify-2d47a.firebaseapp.com',
    storageBucket: 'clinify-2d47a.appspot.com',
    measurementId: 'G-S8B42FP2ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPVDelh7sigulXXgH7iHw4ax--s4s4yg',
    appId: '1:717511155216:android:01f27ce7b80cd5062eb495',
    messagingSenderId: '717511155216',
    projectId: 'clinify-2d47a',
    storageBucket: 'clinify-2d47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjtX0im7el9f55Fz6RVDBlwLffGLAhCps',
    appId: '1:717511155216:ios:685cfea8d51ad3c22eb495',
    messagingSenderId: '717511155216',
    projectId: 'clinify-2d47a',
    storageBucket: 'clinify-2d47a.appspot.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjtX0im7el9f55Fz6RVDBlwLffGLAhCps',
    appId: '1:717511155216:ios:685cfea8d51ad3c22eb495',
    messagingSenderId: '717511155216',
    projectId: 'clinify-2d47a',
    storageBucket: 'clinify-2d47a.appspot.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqGTmcnwvwkK2cZLcU5Cipaefjuqq1QxQ',
    appId: '1:717511155216:web:4207dfcb29cdc4f92eb495',
    messagingSenderId: '717511155216',
    projectId: 'clinify-2d47a',
    authDomain: 'clinify-2d47a.firebaseapp.com',
    storageBucket: 'clinify-2d47a.appspot.com',
    measurementId: 'G-KP226SDPKR',
  );
}
